"""
Layered-segmental circular oversampler (Algorithm 3).

This algorithm decomposes the circle into concentric rings ("layers") and
angular segments aligned with the directions of existing minority points.
Synthetic samples are generated by selecting a random minority point,
perturbing its angular segment, sampling along the segment at a random
layer depth, and adding Gaussian noise.

Two variations are provided:

* **Generic** (``cluster_based=False``): a single circle is formed from
  all minority points.
* **Cluster-based** (``cluster_based=True``): minority points are clustered
  first; the generic procedure is then applied independently within each
  cluster.

Optional IQR-based outlier removal can discard extreme minority points
before the circle is formed.
"""

import numpy as np
from sklearn.cluster import KMeans, AgglomerativeClustering

from src.core.base import BaseOversampler
from src.preprocessing.pca_projection import to_2d, from_2d
from src.utils.geometry import rotate_2d, rotate_batch_2d, perturb_directions_nd, sample_radial_nd
from src.utils.helpers import EPS


class LayeredSegmentalOversampler(BaseOversampler):
    """Layered-segmental circular oversampler.

    Parameters
    ----------
    sampling_strategy : float or int, default=1.0
        Desired minority-to-majority ratio (float) or absolute count (int).
    n_layers : int, default=60
        Number of concentric rings dividing the circle.
    sigma : float, default=0.03
        Standard deviation of radial Gaussian noise (as a fraction of the
        circle radius).
    ang_std : float, default=0.05
        Standard deviation (radians) of the angular perturbation applied
        to the segment direction.
    use_outlier_removal : bool, default=True
        If ``True``, remove IQR-based outliers before computing the circle.
    outlier_keep_frac : float, default=0.95
        Fraction of minority points to retain after outlier removal (the
        bottom ``1 - outlier_keep_frac`` by distance from the centroid are
        discarded).
    cluster_based : bool, default=False
        ``True`` activates the cluster-based variation (one circle per
        cluster).
    K : int, default=3
        Number of clusters when ``cluster_based=True``.
    clustering_method : str, default="kmeans"
        ``"kmeans"`` or ``"hac"`` (hierarchical agglomerative clustering).
    denoise_method : str or None, default=None
        Post-hoc denoising (``"tomek"`` or ``"enn"``).  ``None`` disables.
    minority_label : int, str, or None, default=None
        Explicit minority label; inferred if ``None``.
    random_state : int or None, default=42
        Seed for reproducibility.
    use_pca : bool, default=True
        If ``True``, project to 2-D PCA before all geometry.  If ``False``,
        operate in the original d-D feature space: the centroid-based
        hypersphere, layer radii, direction perturbation, and Gaussian noise
        are all d-dimensional.
    """

    def __init__(
        self,
        sampling_strategy=1.0,
        n_layers=60,
        sigma=0.03,
        ang_std=0.05,
        use_outlier_removal=True,
        outlier_keep_frac=0.95,
        cluster_based=False,
        K=3,
        clustering_method="kmeans",
        denoise_method=None,
        minority_label=None,
        random_state=42,
        use_pca=True,
    ):
        super().__init__(
            sampling_strategy=sampling_strategy,
            minority_label=minority_label,
            random_state=random_state,
            use_pca=use_pca,
        )
        self.n_layers = n_layers
        self.sigma = sigma
        self.ang_std = ang_std
        self.use_outlier_removal = use_outlier_removal
        self.outlier_keep_frac = outlier_keep_frac
        self.cluster_based = cluster_based
        self.K = K
        self.clustering_method = clustering_method
        self.denoise_method = denoise_method

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def fit_resample(self, X, y):
        """Oversample the minority class using layered-segmental generation.

        Parameters
        ----------
        X : ndarray of shape (n_samples, n_features)
        y : ndarray of shape (n_samples,)

        Returns
        -------
        X_resampled : ndarray of shape (n_samples_new, n_features)
        y_resampled : ndarray of shape (n_samples_new,)
        """
        X = np.asarray(X, dtype=np.float64)
        y = np.asarray(y)
        rng = np.random.default_rng(self.random_state)

        min_lab = self._get_minority_label(y)
        n_synth = self._get_n_synth(y, min_lab)
        if n_synth == 0:
            return X.copy(), y.copy()

        X_min = X[y == min_lab]
        n_min = len(X_min)

        # --- Project to working space (2-D PCA or original d-D) ---
        X_min_2d, pca_model = to_2d(
            X_min, random_state=self.random_state or 0, use_pca=self.use_pca
        )

        if self.cluster_based:
            synth_2d = self._cluster_based_generate(X_min_2d, n_synth, rng)
        else:
            synth_2d = self._generic_generate(X_min_2d, n_synth, rng)

        # Lift back.
        X_synth = from_2d(synth_2d, pca_model)

        X_res = np.vstack([X, X_synth])
        y_res = np.concatenate([y, np.full(n_synth, min_lab)])

        # --- Optional denoising ---
        if self.denoise_method is not None:
            X_res, y_res = self._denoise(X_res, y_res)

        return X_res, y_res

    # ------------------------------------------------------------------
    # Generic variation (single circle)
    # ------------------------------------------------------------------

    def _generic_generate(self, X_min_2d, n_synth, rng):
        """Generate synthetic points from a single global circle."""
        X_clean = self._remove_outliers(X_min_2d) if self.use_outlier_removal else X_min_2d
        if len(X_clean) < 2:
            X_clean = X_min_2d  # Fallback.

        center, R, directions = self._build_circle(X_clean)
        return self._sample_from_circle(center, R, X_clean, directions,
                                        n_synth, rng)

    # ------------------------------------------------------------------
    # Cluster-based variation
    # ------------------------------------------------------------------

    def _cluster_based_generate(self, X_min_2d, n_synth, rng):
        """Cluster minority, then apply generic generation per cluster.

        The total *n_synth* samples are distributed among clusters
        proportionally to cluster size.
        """
        K_eff = min(self.K, len(X_min_2d))
        if K_eff <= 1:
            return self._generic_generate(X_min_2d, n_synth, rng)

        cluster_labels = self._cluster(X_min_2d, K_eff, rng)

        # Proportional allocation.
        counts = np.array([
            np.sum(cluster_labels == c) for c in range(K_eff)
        ], dtype=np.float64)
        fracs = counts / counts.sum()
        allocs = np.round(fracs * n_synth).astype(int)
        # Adjust for rounding.
        diff = n_synth - allocs.sum()
        if diff != 0:
            idx = np.argmax(counts)
            allocs[idx] += diff

        chunks = []
        for c in range(K_eff):
            if allocs[c] <= 0:
                continue
            mask = cluster_labels == c
            Xc = X_min_2d[mask]
            if len(Xc) < 2:
                # Too few points -- duplicate with jitter.
                jitter = rng.normal(0, 1e-6, (allocs[c], 2))
                chunks.append(np.tile(Xc[0], (allocs[c], 1)) + jitter)
                continue
            X_clean = self._remove_outliers(Xc) if self.use_outlier_removal else Xc
            if len(X_clean) < 2:
                X_clean = Xc
            center, R, directions = self._build_circle(X_clean)
            chunks.append(
                self._sample_from_circle(center, R, X_clean, directions,
                                         allocs[c], rng)
            )

        return np.vstack(chunks)

    # ------------------------------------------------------------------
    # Circle construction
    # ------------------------------------------------------------------

    @staticmethod
    def _build_circle(X):
        """Compute circle centre, radius, and per-point direction vectors.

        Parameters
        ----------
        X : ndarray of shape (n, 2)
            Minority points (possibly outlier-cleaned).

        Returns
        -------
        center : ndarray of shape (2,)
            Centroid of the points.
        R : float
            Radius = maximum distance from centroid.
        directions : ndarray of shape (n, 2)
            Unit-direction vectors from centre to each point.
        """
        center = X.mean(axis=0)
        diffs = X - center
        dists = np.linalg.norm(diffs, axis=1)
        R = dists.max() if len(dists) > 0 else EPS
        R = max(R, EPS)

        # Normalise to get direction vectors.
        norms = np.maximum(dists, EPS)
        directions = diffs / norms[:, np.newaxis]

        return center, R, directions

    # ------------------------------------------------------------------
    # Sampling from layers and segments
    # ------------------------------------------------------------------

    def _sample_from_circle(self, center, R, X_points, directions,
                            n_synth, rng):
        """Generate synthetic points using the layered-segmental scheme.

        For each synthetic sample:
          1. Pick a random minority point.
          2. Perturb its direction by ``ang_std`` (2-D: angle rotation;
             d-D: Gaussian direction perturbation + renormalisation).
          3. Pick a random layer depth (ring index) uniformly.
          4. Compute the radial position within that layer (area- / volume-
             uniform depending on d).
          5. Place the point along the perturbed direction at that radius.
          6. Add Gaussian noise scaled by ``sigma * R``.
        """
        n_points = len(X_points)
        d = center.shape[0]
        n_layers = self.n_layers

        # Layer boundaries: rings of equal width.
        layer_width = R / max(n_layers, 1)

        # Random minority point indices.
        pt_idx = rng.integers(0, n_points, size=n_synth)
        chosen_dirs = directions[pt_idx]  # (n_synth, d)

        # Perturb directions.
        if d == 2:
            angle_noise = rng.normal(0, self.ang_std, size=n_synth)
            perturbed_dirs = rotate_batch_2d(chosen_dirs, angle_noise)
        else:
            perturbed_dirs = perturb_directions_nd(chosen_dirs, self.ang_std, rng)

        # Random layer indices (0-indexed, 0 = innermost, n_layers-1 = outer).
        layer_idx = rng.integers(0, n_layers, size=n_synth)

        # Radial position: volume-uniform within the layer band.
        # For d-D: r = (U * (r_out^d - r_in^d) + r_in^d)^{1/d}
        # (degenerates to sqrt trick when d == 2)
        r_inner = layer_idx * layer_width
        r_outer = (layer_idx + 1) * layer_width
        radii = sample_radial_nd(rng, r_inner, r_outer, dim=d, n=n_synth)

        # Place along perturbed direction.
        synth = center + radii[:, np.newaxis] * perturbed_dirs

        # Gaussian noise.
        noise = rng.normal(0, self.sigma * R, (n_synth, d))
        synth += noise

        return synth

    # ------------------------------------------------------------------
    # Outlier removal (IQR-based distance filtering)
    # ------------------------------------------------------------------

    def _remove_outliers(self, X):
        """Remove outlier points based on distance to centroid.

        Keeps the closest ``outlier_keep_frac`` fraction of points.
        """
        if len(X) < 4:
            return X

        center = X.mean(axis=0)
        dists = np.linalg.norm(X - center, axis=1)

        n_keep = max(2, int(np.ceil(len(X) * self.outlier_keep_frac)))
        if n_keep >= len(X):
            return X

        # Keep the n_keep closest points.
        keep_idx = np.argsort(dists)[:n_keep]
        return X[keep_idx]

    # ------------------------------------------------------------------
    # Clustering
    # ------------------------------------------------------------------

    def _cluster(self, X, K, rng):
        """Return integer cluster labels for *X*."""
        if K <= 1:
            return np.zeros(len(X), dtype=int)

        if self.clustering_method == "hac":
            model = AgglomerativeClustering(n_clusters=K)
            return model.fit_predict(X)

        seed = int(rng.integers(0, 2**31))
        model = KMeans(n_clusters=K, n_init=10, random_state=seed)
        return model.fit_predict(X)

    # ------------------------------------------------------------------
    # Denoising
    # ------------------------------------------------------------------

    def _denoise(self, X, y):
        """Apply optional post-hoc denoising."""
        method = self.denoise_method
        if method is None:
            return X, y

        if method == "tomek":
            from imblearn.under_sampling import TomekLinks
            tl = TomekLinks()
            return tl.fit_resample(X, y)

        if method == "enn":
            from imblearn.under_sampling import EditedNearestNeighbours
            enn = EditedNearestNeighbours()
            return enn.fit_resample(X, y)

        raise ValueError(f"Unknown denoise method: {method!r}")

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------

    def get_params(self):
        params = super().get_params()
        params.update({
            "n_layers": self.n_layers,
            "sigma": self.sigma,
            "ang_std": self.ang_std,
            "use_outlier_removal": self.use_outlier_removal,
            "outlier_keep_frac": self.outlier_keep_frac,
            "cluster_based": self.cluster_based,
            "K": self.K,
            "clustering_method": self.clustering_method,
            "denoise_method": self.denoise_method,
        })
        return params


